### ISSUE TITLE
pretrain model 

### ISSUE THREAD

**Issue by learning-mamba** [sstary/SSRS#37]
Traceback (most recent call last):
  File "E:\FTransUNet\train.py", line 41, in <module>
    net.load_from(weights=np.load(config_vit.pretrained_path))
  File "E:\FTransUNet\model\vitcross_seg_modeling.py", line 584, in load_from
    unit.load_from(weights, n_block=uname)
  File "E:\FTransUNet\model\vitcross_seg_modeling.py", line 316, in load_from
    query_weight = np2th(weights[pjoin(ROOT, ATTENTION_Q, "kernel")]).view(self.hidden_size, self.hidden_size).t()
  File "E:\Anaconda\envs\bigyu\lib\site-packages\numpy\lib\npyio.py", line 263, in __getitem__
    raise KeyError(f"{key} is not a file in the archive")
KeyError: 'Transformer/encoderblock_0\\MultiHeadDotProductAttention_1/query\\kernel is not a file in the archive'

**Comment by sstary** [comment]
你好，请参考 https://github.com/jeonsworld/ViT-pytorch/issues/11

**Comment by learning-mamba** [comment]
> 你好，请参考 [jeonsworld/ViT-pytorch#11](https://github.com/jeonsworld/ViT-pytorch/issues/11)

谢谢，他是有效的
